CREATE TYPE STATUS AS ENUM ('Manager', 'Seller');
CREATE TABLE person (
	login VARCHAR(255) PRIMARY KEY NOT NULL,
    	password VARCHAR(255) NOT NULL,
    	stat STATUS NOT NULL );
	
CREATE TABLE SUPPLIER (
	id BIGINT PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	phone VARCHAR(30) NOT NULL,
	address VARCHAR(255) NOT NULL );
	
CREATE TABLE COMMODITY (
	id BIGINT PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL
	count BIGINT (count > 0) );
	
CREATE TABLE SUP_ORDER (
	id BIGINT PRIMARY KEY NOT NULL,
	sup_id BIGINT NOT NULL,
	com_id BIGINT NOT NULL,
	count BIGINT CHECK (count > 0),
	CONSTRAINT fk0 FOREIGN KEY (sup_id) REFERENCES supplier(id),
	CONSTRAINT fk1 FOREIGN KEY (com_id) REFERENCES commodity(id) );

CREATE TABLE CLIENT (
	id BIGINT PRIMARY KEY NOT NULL,
	name VARCHAR(255) NOT NULL,
	phone VARCHAR(30) NOT NULL );
	
CREATE TABLE CLIENT_ORDER (
	id BIGINT PRIMARY KEY NOT NULL,
	client_id BIGINT NOT NULL,
	com_id BIGINT NOT NULL,
	count BIGINT CHECK (count > 0),
	CONSTRAINT fk0 FOREIGN KEY (client_id) REFERENCES client(id),
	CONSTRAINT fk1 FOREIGN KEY (com_id) REFERENCES commodity(id) );
